/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bad.robot.unicorn.neopixel;

public class ws2812JNI {
  static {
	System.loadLibrary("ws2812-RPi");
  }
  public final static native void Color_t_r_set(long jarg1, Color_t jarg1_, short jarg2);
  public final static native short Color_t_r_get(long jarg1, Color_t jarg1_);
  public final static native void Color_t_g_set(long jarg1, Color_t jarg1_, short jarg2);
  public final static native short Color_t_g_get(long jarg1, Color_t jarg1_);
  public final static native void Color_t_b_set(long jarg1, Color_t jarg1_, short jarg2);
  public final static native short Color_t_b_get(long jarg1, Color_t jarg1_);
  public final static native long new_Color_t();
  public final static native void delete_Color_t(long jarg1);
  public final static native void init(int jarg1);
  public final static native void clear();
  public final static native void show();
  public final static native long Wheel(short jarg1);
  public final static native void colorWipe(long jarg1, Color_t jarg1_, short jarg2);
  public final static native void rainbow(short jarg1);
  public final static native void rainbowCycle(short jarg1);
  public final static native void theaterChase(long jarg1, Color_t jarg1_, short jarg2);
  public final static native void theaterChaseRainbow(short jarg1);
  public final static native short setBrightness(double jarg1);
  public final static native double getBrightness();
  public final static native long RGB2Color(short jarg1, short jarg2, short jarg3);
  public final static native long Color(short jarg1, short jarg2, short jarg3);
  public final static native short setPixelColor(long jarg1, short jarg2, short jarg3, short jarg4);
  public final static native short setPixelColorT(long jarg1, long jarg2, Color_t jarg2_);
  public final static native long getPixelColor(long jarg1);
  public final static native long numPixels();
  public final static native long getPixels();
  public final static native void setPWMBit(long jarg1, short jarg2);
  public final static native short getPWMBit(long jarg1);
  public final static native void dumpLEDBuffer();
  public final static native void dumpPWMBuffer();
  public final static native void dumpPWMStatus();
  public final static native void dumpPWMControl(long jarg1);
  public final static native void dumpPWMDMAC();
  public final static native void dumpPWM();
  public final static native void dumpDMARegs();
  public final static native void dumpControlBlock(long jarg1);
  public final static native void dumpTransferInformation(long jarg1);
  public final static native void dumpDMA();
  public final static native void terminate(int jarg1);
}
