/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bad.robot.unicorn.integration.jni;

class exampleJNI {
	static {
		System.loadLibrary("example");
	}

	static native void My_variable_set(double jarg1);

	static native double My_variable_get();

	static native int fact(int jarg1);

	static native int my_mod(int jarg1, int jarg2);

	static native String get_time();
}
