/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bad.robot.unicorn.neopixel;

public interface rpi_ws281xConstants {
  public final static int WS2811_TARGET_FREQ = rpi_ws281xJNI.WS2811_TARGET_FREQ_get();
}
