/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bad.robot.unicorn.neopixel.ws2812;

public class Color_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Color_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Color_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ws2812JNI.delete_Color_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setR(short value) {
    ws2812JNI.Color_t_r_set(swigCPtr, this, value);
  }

  public short getR() {
    return ws2812JNI.Color_t_r_get(swigCPtr, this);
  }

  public void setG(short value) {
    ws2812JNI.Color_t_g_set(swigCPtr, this, value);
  }

  public short getG() {
    return ws2812JNI.Color_t_g_get(swigCPtr, this);
  }

  public void setB(short value) {
    ws2812JNI.Color_t_b_set(swigCPtr, this, value);
  }

  public short getB() {
    return ws2812JNI.Color_t_b_get(swigCPtr, this);
  }

  public Color_t() {
    this(ws2812JNI.new_Color_t(), true);
  }

}
